version: '3.8'
services:
  postgresql:
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: opw
      POSTGRES_USER: opw
    image: postgres:15.1-alpine3.17
    networks:
      - onepaas-worker-network
    ports:
      - "5432:5432"

  temporal:
    image: temporalio/auto-setup:1.20.1.0
    container_name: temporal
    depends_on:
      - postgresql
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=opw
      - POSTGRES_PWD=opw
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    networks:
      - onepaas-worker-network
    ports:
      - "7233:7233"
    volumes:
      - ./temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
    labels:
      kompose.volume.type: configMap

  temporal-ui:
    image: temporalio/ui:2.14.0
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    networks:
      - onepaas-worker-network
    ports:
      - "8080:8080"

  worker:
    build:
      context: ../
      dockerfile: dev.dockerfile
    container_name: onepaas-worker
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    networks:
      - onepaas-worker-network

networks:
  onepaas-worker-network:
    driver: bridge
    name: onepaas-worker-network
